### ISSUE TITLE
Improve analytic tracking

### ISSUE THREAD

**Issue by cameronsamuels** [zink-tech/memerator#72]
Google Analytics allows us to create "events" that the user does and track them.

We should do this as we can get more knowledge on how many people actually use the Memerator.

Some events could be:
- [x] Uploaded an image
- [x] Typed something for the top text
- [x] Typed something for the bottom text
- [x] Changed the font (and specific font they changed it to)
- [x] Rotated the image
- [x] Changed the font color
- [x] Download the image
- [ ] Replaced an image

This can let us know more information about how Memerator is used letting us know which features were used more than others.

**Comment by Pipe-to-Grep** [comment]
Can you link me to a forum post or something with instructions?

**Comment by Pipe-to-Grep** [comment]
I know how to do this; however, in order to do it, I need to be able to select buttons by their id. 
Why is there a line in script.js that removes the id?

d('#download').id = '',
d('#advanced').id = '';

**Comment by CameronSamuels** [comment]
Those lines are here because of this css rule:

```css
#download, #advanced {
    display: none!important;
}
```

This means that those elements are hidden. If they don't have the id (like when it is removed on those lines you posted) then it won't be hidden.

**Comment by CameronSamuels** [comment]
To fix your problem, we can use classes to hide them (maybe those 2 elements can have a class of `.hidden`) instead of ids.

This means that those 2 lines of JQuery will only be one line which would be `$('.hidden').removeClass("hidden")` (while converting to JQuery along the way).

This will be better because this causes a problem when replacing an image. So this fixes 2 issues in 1 (plus contributes to the JQuery issue).

That is what you could do next.

**Comment by Pipe-to-Grep** [comment]
I implemented the changes in PR #77 #78 #79

**Comment by Pipe-to-Grep** [comment]
Added POC for downloading the image in PR #80

**Comment by CameronSamuels** [comment]
Good. I merged the 3 pr's for the problems. I will merge the Google Analytics pr later. Good job!

**Comment by Pipe-to-Grep** [comment]
I'll check it off when the download events pop up in GA

**Comment by CameronSamuels** [comment]
Are you testing using GitHub Desktop and your text editor and computer files? If so, great. You should be.

Also, you can let the analytics pop on the GA website by [allowing analytics on the `file:///` protocol](https://stackoverflow.com/questions/3591847/google-analytics-from-a-file-url). Then you will know if it works. Then you can add the other ones to this pull request and merge together.

**Comment by cameronsamuels** [comment]
I'll close this image, and once we fix the replace button, we'll add the GA tracking with it.

Just to say, this project is a mess.
